### ISSUE TITLE
Error running docker

### ISSUE THREAD

**Issue by loviuz** [fsinfuhh/Bitpoll#157]
When I run:

```bash
docker pull ghcr.io/fsinfuhh/bitpoll:latest
```

after run, I get this error:

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 103, in wrapper
    saved_locale = translation.get_language()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/translation/__init__.py", line 210, in get_language
    return _trans.get_language()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/translation/__init__.py", line 65, in __getattr__
    if settings.USE_I18N:
       ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/bitpoll/bitpoll/settings.py", line 406, in <module>
    from .settings_local import *
ModuleNotFoundError: No module named 'bitpoll.settings_local'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitpoll/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 425, in run_from_argv
    connections.close_all()
  File "/usr/local/lib/python3.11/site-packages/django/utils/connection.py", line 84, in close_all
    for conn in self.all(initialized_only=True):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/connection.py", line 76, in all
    return [
           ^
  File "/usr/local/lib/python3.11/site-packages/django/utils/connection.py", line 73, in __iter__
    return iter(self.settings)
                ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/connection.py", line 45, in settings
    self._settings = self.configure_settings(self._settings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 148, in configure_settings
    databases = super().configure_settings(databases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/connection.py", line 50, in configure_settings
    settings = getattr(django_settings, self.settings_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/bitpoll/bitpoll/settings.py", line 406, in <module>
    from .settings_local import *
ModuleNotFoundError: No module named 'bitpoll.settings_local'
```
I also have tried with instructions on README here: https://github.com/fsinfuhh/Bitpoll/pkgs/container/bitpoll

but it is not clear for me what is the right `<workdir>` and `<original_dir>`. Is this a bug?

**Comment by timonegk** [comment]
I updated the install instructions, could you try again and see if they are more clear now?

**Comment by loviuz** [comment]
Thanks! Now the error is:

```bash
NameError: name 'os' is not defined
```

I have tried to edit `settings.py` adding:

```python
import os
```

and the container started. I'm not very familiar with python, but in this way it works. Do you should update the `settings.py`  file?

**Comment by loviuz** [comment]
After this, I can start the container and this is the output:

```bash
System check identified some issues::

django_token_bucket.TokenBucket: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the DjangoTokenBucketConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
Operations to perform:
  Apply all migrations: admin, auth, base, caldav, contenttypes, django_token_bucket, groups, invitations, poll, sessions

Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying base.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying base.0002_auto_20170419_1407... OK
  Applying base.0002_auto_20170419_1121... OK
  Applying base.0003_merge_20170419_1403... OK
  Applying base.0004_dudeluser_displayname... OK
  Applying base.0005_auto_20171017_1320... OK
  Applying base.0006_auto_20180704_1421... OK
  Applying base.0007_auto_20220129_1728... OK
  Applying base.0008_alter_bitpolluser_first_name... OK
  Applying caldav.0001_initial_new... OK
  Applying caldav.0002_auto_20180712_1509... OK
  Applying django_token_bucket.0001_initial... OK
  Applying django_token_bucket.0002_auto_20191216_1228... OK
  Applying django_token_bucket.0003_auto_20200111_1625... OK
  Applying django_token_bucket.0004_auto_20200111_1625... OK
  Applying groups.0001_initial... OK
  Applying poll.0001_initial... OK
  Applying poll.0002_auto_20170309_1709... OK
  Applying poll.0003_auto_20170310_2102... OK
  Applying invitations.0001_initial... OK
  Applying invitations.0002_auto_20170310_2202... OK
  Applying invitations.0003_auto_20170315_2046... OK
  Applying invitations.0004_auto_20170315_2113... OK
  Applying poll.0003_auto_20170310_2259... OK
  Applying poll.0004_merge_20170310_2224... OK
  Applying poll.0005_auto_20170324_1034... OK
  Applying poll.0006_auto_20170328_1958... OK
  Applying poll.0007_auto_20170419_1407... OK
  Applying poll.0007_auto_20170419_1121... OK
  Applying poll.0008_merge_20170419_1403... OK
  Applying poll.0009_poll_vote_all... OK
  Applying poll.0010_choicevalue_deleted... OK
  Applying poll.0011_auto_20170426_1631... OK
  Applying poll.0012_poll_use_user_timezone... OK
  Applying poll.0013_auto_20171017_1320... OK
  Applying poll.0014_auto_20171017_1530... O
  Applying poll.0015_poll_hide_participants... OK
  Applying poll.0016_auto_20171114_1536... OK
  Applying poll.0017_poll_allow_unauthenticated_vote_changes... OK
  Applying poll.0018_poll_show_score_in_summary... OK
  Applying poll.0019_alter_choice_id_alter_choicevalue_id_and_more... OK
  Applying sessions.0001_initial... OK
[uWSGI] getting INI configuration from /etc/uwsgi/bitpoll.ini

*** Starting uWSGI 2.0.21-debian (64bit) on [Fri Jan 19 21:50:12 2024] ***
compiled with version: 12.2.0 on 19 May 2023 13:59:29
os: Linux-6.1.0-17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30)
nodename: b912bb0b2850
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /opt/bitpoll
detected binary path: /usr/bin/uwsgi-core
setgid() to 33
setuid() to 2008
chdir() to /opt/bitpoll
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :3008 fd 3
Python version: 3.11.7 (main, Jan 11 2024, 10:43:21) [GCC 12.2.0]
Set PythonHome to /usr/local
Python main interpreter initialized at 0x7f859c600ed8
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 938592 bytes (916 KB) for 32 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x7f859c600ed8 pid: 7 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 7)
spawned uWSGI worker 1 (pid: 11, cores: 4)
spawned uWSGI worker 2 (pid: 15, cores: 4)
-- unavailable modifier requested: 22 --
```

When I open `http://<address>:3009` the server refuse connection. If I connect to 3008 I see some output to the docker console like an error, so the server seems to respond on ports 3008 and 3009, but on port 3009 I cannot get a connection.

**Comment by ftsell** [comment]
> and the container started. I'm not very familiar with python, but in this way it works. Do you should update the `settings.py` file?

To answer your question: yes
Managing settings in django has always been kind of clunky because in my opinion you shouldn't have to deal with source code (which this essentially is) and define some variables that django expects if you just want an application up and running. We have plans to make this easier in the future but haven't gotten around to do it yet.

**Comment by timonegk** [comment]
The connection refused error was due to a bad uwsgi configuration. I created a pull request that should fix the issue and some other deployment problems.
